#include "camellia_expansion.h"


const uint64_t Sigma1 = 0xA09E667F3BCC908Bul;
const uint64_t Sigma2 = 0xB67AE8584CAA73B2ul;
const uint64_t Sigma3 = 0xC6EF372FE94F82BEul;
const uint64_t Sigma4 = 0x54FF53A5F1D36F1Cul;

// only used for keylen > 128
const uint64_t Sigma5 = 0x10E527FADE682D1Dul;
const uint64_t Sigma6 = 0xB05688C2B3E6C1FDul;


uint64_t rol128lo(uint64_t xhi, uint64_t xlo, unsigned n) {
    if (n > 64) {
        return n? (xhi << (n - 64)) | (xlo >> (128 - n)) : xhi;
    } else {
        return n? (xlo << n) | (xhi >> (64 - n)) : xlo;
    }
}

#define rol128hi(xhi, xlo, n) rol128lo(xlo, xhi, n)

// generate 64-bit subkeys kw1, ..., kw4, k1, ..., k18, ke1, ..., ke4
// the subkeys are concatenated stored concatenated into a single array
// exkey = kw | k | ke
void camellia_expandkey(uint64_t *user_key, uint64_t *exkey, size_t keylen) {
    uint64_t K[4];
    uint64_t *kw, uint64_t *k, uint64_t *ke;

    K[0] = user_key[0]; K[1] = user_key[1];

    if (keylen == 128) {
        K[2] = 0; K[3] = 0;
        kw = exkey; k = exkey + 4; ke = exkey + 22;
    } else if (keylen == 128) {
        K[2] = user_key[2]; K[3] = ~user_key[2];
        kw = exkey; k = exkey + 4; ke = exkey + 28;
    } else {
        K[2] = user_key[2]; K[3] = user_key[3];
        kw = exkey; k = exkey + 4; ke = exkey + 28;
    }

    uint64_t KLhi = K[0];
    uint64_t KLlo = K[1];
    uint64_t KRhi = K[2];
    uint64_t KRlo = K[3];

    uint64_t D1, D2;

    D1 = KLhi ^ KRhi;
    D2 = KLlo ^ KRlo;
    D2 = D2 ^ F(D1, Sigma1);
    D1 = D1 ^ F(D2, Sigma2);
    D1 = D1 ^ KLhi;
    D2 = D2 ^ KLlo;
    D2 = D2 ^ F(D1, Sigma3);
    D1 = D1 ^ F(D2, Sigma4);

    uint64_t KAhi = D1;
    uint64_t KAlo = D2;

    if (keylen > 128) {
        D1 = KAhi ^ KRhi;
        D2 = KAlo ^ KRlo;
        D2 = D2 ^ F(D1, Sigma5);
        D1 = D1 ^ F(D2, Sigma6);
    }


    // only used for keylen > 128
    uint64_t KBhi = D1;
    uint64_t KBlo = D2;

    // 64-bit subkeys are generated by rotating KL, KR, KA, and KB and
    // taking the left- or right-half of them.

    if (keylen == 128) {
        kw[0] = rol128hi(KLhi, KLlo,   0);
        kw[1] = rol128lo(KLhi, KLlo,   0);

        k[0]  = rol128hi(KAhi, KAlo,   0);
        k[1]  = rol128lo(KAhi, KAlo,   0);
        k[2]  = rol128hi(KLhi, KLlo,  15);
        k[3]  = rol128lo(KLhi, KLlo,  15);
        k[4]  = rol128hi(KAhi, KAlo,  15);
        k[5]  = rol128lo(KAhi, KAlo,  15);

        ke[0] = rol128hi(KAhi, KAlo,  30);
        ke[1] = rol128lo(KAhi, KAlo,  30);

        k[6]  = rol128hi(KLhi, KLlo,  45);
        k[7]  = rol128lo(KLhi, KLlo,  45);
        k[8]  = rol128hi(KAhi, KAlo,  45);
        k[9]  = rol128lo(KLhi, KLlo,  60);
        k[10] = rol128hi(KAhi, KAlo,  60);
        k[11] = rol128lo(KAhi, KAlo,  60);

        ke[2] = rol128hi(KLhi, KLlo,  77);
        ke[3] = rol128lo(KLhi, KLlo,  77);

        k[12] = rol128hi(KLhi, KLlo,  94);
        k[13] = rol128lo(KLhi, KLlo,  94);
        k[14] = rol128hi(KAhi, KAlo,  94);
        k[15] = rol128lo(KAhi, KAlo,  94);
        k[16] = rol128hi(KLhi, KLlo, 111);
        k[17] = rol128lo(KLhi, KLlo, 111);

        kw[2] = rol128hi(KAhi, KAlo, 111);
        kw[3] = rol128lo(KAhi, KAlo, 111);
    }
    else { // 192 or 256
        kw[0] = rol128hi(KLhi, KLlo,   0);
        kw[1] = rol128lo(KLhi, KLlo,   0);

        k[0]  = rol128hi(KBhi, KBlo,   0);
        k[1]  = rol128lo(KBhi, KBlo,   0);
        k[2]  = rol128hi(KRhi, KRlo,  15);
        k[3]  = rol128lo(KRhi, KRlo,  15);
        k[4]  = rol128hi(KAhi, KAlo,  15);
        k[5]  = rol128lo(KAhi, KAlo,  15);

        ke[0] = rol128hi(KRhi, KRlo,  30);
        ke[1] = rol128lo(KRhi, KRlo,  30);

        k[6]  = rol128hi(KBhi, KBlo,  30);
        k[7]  = rol128lo(KBhi, KBlo,  30);
        k[8]  = rol128hi(KLhi, KLlo,  45);
        k[9]  = rol128lo(KLhi, KLlo, 45);
        k[10] = rol128hi(KAhi, KAlo,  45);
        k[11] = rol128lo(KAhi, KAlo,  45);

        ke[2] = rol128hi(KLhi, KLlo,  60);
        ke[3] = rol128lo(KLhi, KLlo,  60);

        k[12] = rol128hi(KRhi, KRlo,  60);
        k[13] = rol128lo(KRhi, KRlo,  60);
        k[14] = rol128hi(KBhi, KBlo,  60);
        k[15] = rol128lo(KBhi, KBlo,  60);
        k[16] = rol128hi(KLhi, KLlo,  77);
        k[17] = rol128lo(KLhi, KLlo,  77);

        ke[4] = rol128hi(KAhi, KAlo,  77);
        ke[5] = rol128lo(KAhi, KAlo,  77);

        k[18] = rol128hi(KRhi, KRlo,  94);
        k[19] = rol128lo(KRhi, KRlo,  94);
        k[20] = rol128hi(KAhi, KAlo,  94);
        k[21] = rol128lo(KAhi, KAlo,  94);
        k[22] = rol128hi(KLhi, KLlo, 111);
        k[23] = rol128lo(KLhi, KLlo, 111);

        kw[2] = rol128hi(KBhi, KBlo, 111);
        kw[3] = rol128lo(KBhi, KBlo, 111);
    }
}
